apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: evite-mono-gateway
  namespace: evite-mono
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "evite-mono.com"
        - "www.evite-mono.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: evite-mono
  namespace: evite-mono
spec:
  hosts:
    - "evite-mono.com"
    - "www.evite-mono.com"
  gateways:
    - evite-mono-gateway
  http:
    - route:
        - destination:
            host: evite-mono
            port:
              number: 4020
---
apiVersion: v1
kind: Service
metadata:
  name: evite-mono
  namespace: evite-mono
  labels:
    app: evite-mono
    service: evite-mono
spec:
  ports:
    - port: 4020
      name: http
  selector:
    app: evite-mono
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: evite-mono
  namespace: evite-mono
  labels:
    app: evite-mono
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evite-mono
      version: v1
  template:
    metadata:
      labels:
        app: evite-mono
        version: v1
    spec:
      containers:
        - name: evite-mono
          image: registry.gitlab.com/mernxl-evite/evite-mono:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGODB_USER_NAME
              value: root
            - name: MONGODB_USER_PASS
              value: e3R6SCf404dif-Nm
            - name: MONGODB_URL
              value: mongodb://mongodb-0.mongodb-headless.mongodb.svc.cluster.local:27017,mongodb-1.mongodb-headless.mongodb.svc.cluster.local:27017,mongodb-2.mongodb-headless.mongodb.svc.cluster.local:27017/?replicaSet=rs0
            - name: SERVER_HOST
              value: 0.0.0.0
            - name: SERVER_PORT
              value: "4020"
            - name: NODE_ENV
              value: production
            - name: JWT_SECRET
              value: wb0GVijnquSCyRy7tte5kv7XfyVol9CoJozcZcKcKEI=
          ports:
            - containerPort: 4020
---
