kind: Namespace
apiVersion: v1
metadata:
  name: evite-mono
  labels:
    name: evite-mono
    istio-injection: enabled
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: evite-config
  namespace: evite-mono
data:
  AUTH_JWT_SECRET: wb0GVijnquSCyRy7tte5kv7XfyVol9CoJozcZcKcKEI=
  EVENT_BUCKET_NAME: evites-mono--events-dev
  CRYPTO_SYSTEM_SECRET: wb0GVijnquSCyRy7tte5kv7XfyVol9CoJozcZcKcKEI=

  # MINIO_ENDPOINT: s3.eu-north-1.amazonaws.com
  # MINIO_REGION: eu-north-1
  # MINIO_USE_SSL: True
  # MINIO_PORT: 443
  # MINIO_ACCESS_KEY: AKIA2IVUZ7AA5LKQDKUD
  # MINIO_SECRET_KEY: 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

  MINIO_ENDPOINT: minio.minio.svc.cluster.local
  MINIO_REGION: cm-north-1
  MINIO_USE_SSL: 'True'
  MINIO_PORT: '9000'
  MINIO_ACCESS_KEY: root
  MINIO_SECRET_KEY: e3R6SCf404dif-Nm

  MONGODB_URL: mongodb://mongodb-0.mongodb-headless.mongodb.svc.cluster.local:27017,mongodb-1.mongodb-headless.mongodb.svc.cluster.local:27017,mongodb-2.mongodb-headless.mongodb.svc.cluster.local:27017/?replicaSet=rs0
  MONGODB_USER_NAME: root
  MONGODB_USER_PASS: e3R6SCf404dif-Nm

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: evite-mono-gateway
  namespace: evite-mono
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "evite-mono.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: evite-mono
  namespace: evite-mono
spec:
  hosts:
    - "evite-mono.com"
  gateways:
    - evite-mono-gateway
  http:
    - route:
        - destination:
            host: evite-mono
            port:
              number: 4020
---
apiVersion: v1
kind: Service
metadata:
  name: evite-mono
  namespace: evite-mono
  labels:
    app: evite-mono
    service: evite-mono
spec:
  ports:
    - port: 4020
      name: http
  selector:
    app: evite-mono
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: evite-mono
  namespace: evite-mono
  labels:
    app: evite-mono
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evite-mono
      version: v1
  template:
    metadata:
      labels:
        app: evite-mono
        version: v1
    spec:
      containers:
        - name: evite-mono
          image: registry.gitlab.com/mernxl-evite/evite-mono:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: evite-config
                  key: AUTH_JWT_SECRET
            - name: EVENT_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: evite-config
                  key: EVENT_BUCKET_NAME
            - name: MONGODB_USER_NAME
              valueFrom:
                configMapKeyRef:
                  name: evite-config
                  key: MONGODB_USER_NAME
            - name: MONGODB_USER_PASS
              valueFrom:
                configMapKeyRef:
                  name: evite-config
                  key: MONGODB_USER_PASS
            - name: MONGODB_URL
              valueFrom:
                configMapKeyRef:
                  name: evite-config
                  key: MONGODB_URL
            - name: MINIO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: evite-config
                  key: MINIO_ENDPOINT
            - name: MINIO_REGION
              valueFrom:
                configMapKeyRef:
                  name: evite-config
                  key: MINIO_REGION
            - name: MINIO_PORT
              valueFrom:
                configMapKeyRef:
                  name: evite-config
                  key: MINIO_PORT
            - name: MINIO_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: evite-config
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: evite-config
                  key: MINIO_SECRET_KEY

            - name: SERVER_HOST
              value: 0.0.0.0
            - name: SERVER_PORT
              value: "4020"
            - name: NODE_ENV
              value: production
            - name: SMTP_USER_PASS
              value: ""
            - name: SMTP_USER_NAME
              value: ""
          ports:
            - containerPort: 4020
---
